# Generated by Django 3.0.8 on 2020-08-27 00:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Gold', 'gold'), ('Silver', 'silver'), ('Bronze', 'bronze')], default='Bronze', max_length=30, null=True),
        ),
    ]
