# Generated by Django 3.0.8 on 2020-08-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20200827_0011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Gold', 'gold'), ('Silver', 'silver'), ('Bronze', 'bronze')], default='Bronze', max_length=30),
        ),
    ]
