# Generated by Django 3.0.8 on 2020-08-28 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0004_auto_20200828_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(choices=[('Gold', 'gold'), ('Silver', 'silver'), ('Bronze', 'bronze'), ('Free', 'free')], default='Free', max_length=50),
        ),
    ]
