# Generated by Django 3.0.8 on 2020-08-28 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0005_auto_20200828_2317'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='name',
            field=models.CharField(default=30, max_length=20),
        ),
    ]
