# Generated by Django 3.0.8 on 2020-08-27 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plans',
            name='plan_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
