# Generated by Django 3.0.8 on 2020-08-28 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='allow_memberships',
            new_name='allowed_memberships',
        ),
    ]
